### ISSUE TITLE
Unable to build on Mac OS 10.14

### ISSUE THREAD

**Issue by simsong** [libyal/libewf-legacy#1]
Operating system: 10.14.2
MacPorts.
Clean install

```
Making all in libcaes
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -I../libcerror  -I/opt/local/include/ -I/opt/local/include  -g -O2 -Wall -MT libcaes_context.lo -MD -MP -MF .deps/libcaes_context.Tpo -c -o libcaes_context.lo libcaes_context.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common -I../libcerror -I/opt/local/include/ -I/opt/local/include -g -O2 -Wall -MT libcaes_context.lo -MD -MP -MF .deps/libcaes_context.Tpo -c libcaes_context.c -o libcaes_context.o
libcaes_context.c:365:6: error: use of undeclared identifier 'libcaes_tables_initialized'; did you mean 'libcaes_context_initialize'?
        if( libcaes_tables_initialized == 0 )
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
            libcaes_context_initialize
libcaes_context.c:258:5: note: 'libcaes_context_initialize' declared here
int libcaes_context_initialize(
    ^
libcaes_context.c:365:6: warning: comparison of function 'libcaes_context_initialize' equal to a null pointer is always false
      [-Wtautological-pointer-compare]
        if( libcaes_tables_initialized == 0 )
            ^~~~~~~~~~~~~~~~~~~~~~~~~~    ~
libcaes_context.c:365:6: note: prefix with the address-of operator to silence this warning
        if( libcaes_tables_initialized == 0 )
            ^
            &
libcaes_context.c:379:3: error: use of undeclared identifier 'libcaes_tables_initialized'
                libcaes_tables_initialized = 1;
                ^
libcaes_context.c:2819:5: warning: implicit declaration of function 'libcaes_calculate_forward_table_round' is invalid in C99
      [-Wimplicit-function-declaration]
                                libcaes_calculate_forward_table_round(
                                ^
libcaes_context.c:2835:4: warning: implicit declaration of function 'libcaes_calculate_forward_table_round' is invalid in C99
      [-Wimplicit-function-declaration]
                        libcaes_calculate_forward_table_round(
                        ^
libcaes_context.c:2843:4: warning: implicit declaration of function 'libcaes_calculate_forward_substitution_round' is invalid in C99
      [-Wimplicit-function-declaration]
                        libcaes_calculate_forward_substitution_round(
                        ^
libcaes_context.c:2855:5: warning: implicit declaration of function 'libcaes_calculate_reverse_table_round' is invalid in C99
      [-Wimplicit-function-declaration]
                                libcaes_calculate_reverse_table_round(
                                ^
libcaes_context.c:2871:4: warning: implicit declaration of function 'libcaes_calculate_reverse_table_round' is invalid in C99
      [-Wimplicit-function-declaration]
                        libcaes_calculate_reverse_table_round(
                        ^
libcaes_context.c:2879:4: warning: implicit declaration of function 'libcaes_calculate_reverse_substitution_round' is invalid in C99
      [-Wimplicit-function-declaration]
                        libcaes_calculate_reverse_substitution_round(
                        ^
7 warnings and 2 errors generated.
make[1]: *** [libcaes_context.lo] Error 1
make: *** [all-recursive] Error 1
nimi:libewf-legacy simsong$ 
```

**Comment by joachimmetz** [comment]
Did you check out the code from git or downloaded a source distribution package (if so which version)?

Also see: https://github.com/libyal/libewf/wiki/Building#read-first

**Comment by joachimmetz** [comment]
@simsong I'm unable to reproduce this with libewf-20140804.tar.gz. Could you indicate how you obtained the source?

**Comment by simsong** [comment]
I downloaded the source from github. Apparently the problem is a permissions problem; `/mnt/ewf` is only accessible from the root account.

**Comment by joachimmetz** [comment]
I assume it was a copy of git HEAD then, I'll have a look when time permits.

**Comment by joachimmetz** [comment]
dependency on libcaes has been removed, it was included to work on encrypted Ex01 support but that will not be implemented in the legacy version of libewf.
